[defaults]
target = "example_passthrough"
sim    = "ghdl"
waves  = true

[targets.example_passthrough]
description = "Sanity target for AXI4-Video passthrough pipeline checks."
toplevel    = "example_passthrough"
test_module = "tests.test_passthrough"
sources     = ["rtl/EXAMPLE_PASSTHROUGH/hdl/*.vhd"]

[targets.test_example]
description = "Run legacy single-frame example tests only (tests.test_example)."
toplevel    = "example_passthrough"
test_module = "tests.test_example"
sources     = ["rtl/EXAMPLE_PASSTHROUGH/hdl/example_passthrough.vhd"]

[targets.axi_rgb_to_grayscale]
description = "AXI4-Stream RGB to grayscale transform checks."
toplevel    = "axirgbtograyscale"
test_module = "tests.test_axi_rgb_to_grayscale"
sources     = ["rtl/RGB_TO_GRAYSCALE/hdl/*.vhd"]

[targets.test_debouncer]
description = "Debouncer checks."
toplevel    = "debouncer"
test_module = "tests.test_debouncing"
sources     = ["rtl/DEBOUNCER/hdl/*.vhd"]

[targets.test_click_detector]
description = "Click Detector checks."
toplevel    = "clickdetector"
test_module = "tests.test_click_detection"
sources     = ["rtl/CLICK_DETECTOR/hdl/*.vhd"]
